### PR TITLE
 Add Tabbed-Bookmarks-Manager to Master branch 

### PR DESCRIPTION
**Pull request by tbpassin**
This PR is intended to add the Tabbed-Bookmarks-Manager from my own leo-editor-contrib branch to Leo's leo-editor-contrib master branch.

### CODE REVIEW

**Comment by edreamleo** [comment]
@tbpassin Alas, this PR still says (at the top): [tbpassin](https://github.com/tbpassin) wants to merge 2 commits into [leo-editor:master](https://github.com/leo-editor/leo-editor-contrib) from [tbpassin:devel](https://github.com/tbpassin/leo-editor-contrib/tree/devel).

**Comment by tbpassin** [comment]
This is misleading signage on the part of GitHub.  I was on the leo-editor-contrib site when  created the PR, and I chose the leo-editor-contrib/master branch from the drop down as the target.  That's what I did the time before, so I was extra careful about what the dropdown said this time.

If you actually copy the link address of my repo, where it says "tpassin:devel:, that actual copied address is "https://github.com/tbpassin/leo-editor-contrib/tree/devel".  If you copy the actual link address that is labeled "leo-editor:master", the actual link address is "https://github.com/leo-editor/leo-editor-contrib".

I infer that the PR is going from the right place to the intended destination.  If that's not the case, someone will have to tell me how to do this because I have no idea what to do next.

**Comment by edreamleo** [comment]
@tbpassin I'm going to see what I can do about this.

**Comment by edreamleo** [comment]
@tbpassin Everything went well, as you implied it would. I `cd`'d to the `leo-editor-contrib` repo, pulled from `master`, and got the expected files.

**Pull request merged**
